export const META_ANGLES = [
  "pain",
  "desire",
  "before_after",
  "social_proof",
  "authority",
  "scarcity",
  "urgency",
  "deal_savings",
  "simplicity",
  "speed",
  "guarantee",
  "objection",
  "lifestyle",
  "ugc",
  "comparison",
  "feature_focus",
  "benefit_focus",
  "fear_of_missing_out",
  "status_identity",
  "seasonal",
  "gift",
  "problem_solution",
  "myth_busting",
  "results",
  "bundle",
  "premium",
  "eco",
  "comfort",
  "performance",
  "minimal",
] as const;

export type MetaAngle = (typeof META_ANGLES)[number];
