/**
 * Template: Bebas Neue Urgencia
 *
 * Full-bleed urgency/pain-point scene with a single oversized Bebas Neue headline:
 *   OVERLAY:   dark semi-transparent solid tint over full canvas (~52% opacity)
 *   HEADLINE:  single powerful claim, Bebas Neue, uppercase, white, left-anchored, top area
 *   LOGO:      top-left, auto-rendered by system
 *   SCENE:     urgency/pain-point person generated by PRODUCT_IA (full-bleed, no product)
 *
 * No product layer. copyZone = "center" → full-bleed scene generation.
 *
 * TemplateCopy fields:
 *   headline — single impactful pain-point or urgency claim, max 8 words
 */

import type { LayoutSpec } from "../layoutSpec";
import type { TemplateCopy } from "./classic-editorial";

// ── Text measurement (Bebas Neue condensed) ──────────────────────────────────

const CHAR_WIDTHS: Record<string, number> = {
  i: 0.25,
  l: 0.25,
  I: 0.28,
  "!": 0.28,
  ".": 0.28,
  ",": 0.28,
  "¿": 0.38,
  "?": 0.42,
  "@": 0.65,
  j: 0.28,
  f: 0.32,
  t: 0.35,
  r: 0.38,
  "1": 0.45,
  s: 0.48,
  c: 0.5,
  a: 0.52,
  e: 0.52,
  o: 0.55,
  n: 0.55,
  u: 0.55,
  z: 0.48,
  x: 0.5,
  v: 0.5,
  y: 0.5,
  k: 0.52,
  h: 0.55,
  b: 0.55,
  d: 0.55,
  p: 0.55,
  q: 0.55,
  g: 0.55,
  w: 0.72,
  m: 0.82,
  W: 0.95,
  M: 0.88,
  A: 0.65,
  B: 0.62,
  C: 0.65,
  D: 0.68,
  E: 0.55,
  F: 0.52,
  G: 0.7,
  H: 0.7,
  J: 0.45,
  K: 0.62,
  L: 0.52,
  N: 0.7,
  O: 0.72,
  P: 0.58,
  Q: 0.72,
  R: 0.62,
  S: 0.55,
  T: 0.58,
  U: 0.68,
  V: 0.62,
  X: 0.62,
  Y: 0.58,
  Z: 0.58,
  "0": 0.55,
  "2": 0.55,
  "3": 0.55,
  "4": 0.55,
  "5": 0.55,
  "6": 0.55,
  "7": 0.55,
  "8": 0.55,
  "9": 0.55,
  " ": 0.28,
  "-": 0.35,
  "%": 0.85,
  "&": 0.7,
  á: 0.52,
  é: 0.52,
  í: 0.25,
  ó: 0.55,
  ú: 0.55,
  ñ: 0.55,
  Á: 0.65,
  É: 0.55,
  Ó: 0.72,
  Ú: 0.68,
  Ñ: 0.7,
};

const DEFAULT_CW = 0.55;

// Must match textRenderer's FONT_FAMILY_FACTORS["bebas neue"] for consistent measurement
const BEBAS_FACTOR = 0.80;

function measureBebasWord(text: string, fontSize: number): number {
  let w = 0;
  for (const ch of text.toUpperCase())
    w += (CHAR_WIDTHS[ch] ?? DEFAULT_CW) * fontSize;
  return w * BEBAS_FACTOR;
}

/**
 * Reduce fontSize until the word-wrapped text fits within `maxLines` lines.
 * Starts at startSize and decrements by 2px until the wrap count ≤ maxLines or minSize is reached.
 */
function fitBebasToLines(
  text: string,
  maxWidth: number,
  maxLines: number,
  startSize: number,
  minSize: number,
): number {
  const words = text.toUpperCase().split(/\s+/).filter(Boolean);
  if (words.length === 0) return startSize;

  function countLines(size: number): number {
    const spaceW = measureBebasWord(" ", size);
    let lineWidth = 0;
    let lines = 1;
    for (const word of words) {
      const ww = measureBebasWord(word, size);
      if (lineWidth > 0 && lineWidth + spaceW + ww > maxWidth) {
        lines++;
        lineWidth = ww;
      } else {
        lineWidth = lineWidth === 0 ? ww : lineWidth + spaceW + ww;
      }
    }
    return lines;
  }

  let size = startSize;
  while (size > minSize && countLines(size) > maxLines) {
    size -= 2;
  }
  return size;
}

// ── Layout builder ────────────────────────────────────────────────────────────

export function buildBebasUrgenciaTopLayout(
  copy: TemplateCopy,
  canvas = { width: 1080, height: 1080 },
): LayoutSpec {
  const { width: CW, height: CH } = canvas;
  const MARGIN = Math.round(CW * 0.04); // ~43px

  // ── Headline sizing ──────────────────────────────────────────────────────
  // Symmetric margins so centering anchors at CW/2
  const HL_X = MARGIN;
  const HL_W = CW - 2 * MARGIN; // ~994px — anchor at MARGIN + HL_W/2 = CW/2
  // Moderate-large display size — only shrinks if a single word overflows
  const HL_MAX_FS = Math.round(CW * 0.115); // ~124px for 1080
  const HL_MIN_FS = Math.round(CW * 0.065); // ~70px floor
  const HL_LINE_H = 0.95; // Bebas Neue tight line-height

  const MAX_HL_LINES = 2;
  const rawHeadline = copy.headline ?? "";
  const hlFontSize = fitBebasToLines(rawHeadline, HL_W, MAX_HL_LINES, HL_MAX_FS, HL_MIN_FS);

  // Estimate wrapped line count for height allocation (word-wrap at HL_W)
  const spaceW = measureBebasWord(" ", hlFontSize);
  const words = rawHeadline.toUpperCase().split(/\s+/).filter(Boolean);
  let lineWidth = 0;
  let lineCount = 1;
  for (const word of words) {
    const ww = measureBebasWord(word, hlFontSize);
    if (lineWidth > 0 && lineWidth + spaceW + ww > HL_W) {
      lineCount++;
      lineWidth = ww;
    } else {
      lineWidth = lineWidth === 0 ? ww : lineWidth + spaceW + ww;
    }
  }
  const hlLines = Math.min(lineCount, MAX_HL_LINES);
  const HL_H = Math.ceil(hlFontSize * HL_LINE_H * hlLines) + 20;

  // ── Vertical position: start at ~10% to leave room for logo ─────────────
  const HL_Y = Math.round(CH * 0.10);

  return {
    version: "1",
    canvas: { width: CW, height: CH },
    safeArea: { margin: MARGIN },

    // No product — full-bleed urgency scene handled by PRODUCT_IA
    product: {
      anchor: "custom",
      x: 0,
      y: 0,
      width: 0,
      height: 0,
      scale: 1,
      rotation: 0,
    },

    overlays: [
      // Dark semi-transparent tint over full canvas for text legibility
      {
        type: "solid",
        x: 0,
        y: 0,
        w: CW,
        h: CH,
        color: "#000000",
        opacity: 0.52,
      },
    ],

    textBlocks: [
      // ── HEADLINE: Bebas Neue, centered, top area ─────────────────────────
      {
        id: "headline",
        content: rawHeadline,
        x: HL_X,
        y: HL_Y,
        w: HL_W,
        h: HL_H,
        align: "center",
        fontFamily: "Bebas Neue",
        fontWeight: "400",
        fontSize: hlFontSize,
        color: "#FFFFFF",
        lineHeight: HL_LINE_H,
        letterSpacing: 0.01,
        maxLines: MAX_HL_LINES,
        textTransform: "uppercase",
      },
    ],

    confidence: 1,
    rationale:
      "bebas-urgencia-top — Full-bleed urgency scene, single oversized Bebas Neue headline top-left, dark solid overlay. Logo auto top-left. No product.",
    warnings: [
      "No product — urgency scene generated by PRODUCT_IA (full-bleed).",
      "Dark solid overlay (52% opacity) ensures white text readability over scene.",
      "Bebas Neue: condensed display font, uppercase. Single headline only.",
    ],
  } as unknown as LayoutSpec;
}
