/**
 * Template: Editorial Center Top
 *
 * Headline + subheadline centrados en la parte superior del creativo.
 * Persona/escena lifestyle generada por IA ocupa el ancho completo inferior.
 * Estilo editorial beauty premium. Sin producto.
 *
 * Gemini usa zoneHint="top" → persona en el 50% inferior, top 50% intacto.
 * Sharp aplica protección bulletproof: restaura el bg original en la zona de texto.
 *
 * TemplateCopy fields:
 *   headline     — claim principal centrado (max 3 líneas, Lora italic bold)
 *   subheadline  — bajada complementaria centrada (Montserrat medium)
 *   badge        — URL o tagline pequeño sobre el headline (overline)
 *   cta          — texto del botón al pie (pill sobre la persona)
 *   sceneAction  — descripción de la persona/escena para Gemini
 */

import type { LayoutSpec } from "../layoutSpec";
import type { TemplateCopy } from "./classic-editorial";

// ── Text-balance break: splits into exactly 2 lines at the most balanced point ─
function balanceBreak(text: string): string {
  if (!text) return text;
  const words = text.trim().split(/\s+/);
  if (words.length <= 1) return text;

  let bestSplit = Math.ceil(words.length / 2);
  let bestDiff = Infinity;
  for (let i = 1; i < words.length; i++) {
    const diff = Math.abs(
      words.slice(0, i).join(" ").length - words.slice(i).join(" ").length,
    );
    if (diff < bestDiff) { bestDiff = diff; bestSplit = i; }
  }
  return words.slice(0, bestSplit).join(" ") + "\n" + words.slice(bestSplit).join(" ");
}

// ── Layout builder ────────────────────────────────────────────────────────────

export function buildEditorialCenterTopLayout(
  copy: TemplateCopy,
  canvas = { width: 1080, height: 1080 },
): LayoutSpec {
  const { width: CW, height: CH } = canvas;

  // ── Headline: always exactly 2 lines, text-balanced ─────────────────────
  const headlineWords = (copy.headline ?? "").trim().split(/\s+/).filter(Boolean).length;
  const HEADLINE_FONT = Math.round(
    CW * (headlineWords <= 4 ? 0.088 : headlineWords <= 6 ? 0.074 : 0.062),
  );
  const balancedHeadline = balanceBreak(copy.headline ?? "");
  const HEADLINE_W = Math.round(CW * 0.88);
  const HEADLINE_X = Math.round((CW - HEADLINE_W) / 2);
  const HEADLINE_Y = Math.round(CH * 0.14);
  const HEADLINE_H = Math.ceil(HEADLINE_FONT * 1.1 * 2) + 12; // fixed 2 lines

  // ── Subheadline: centered, dynamically below headline ────────────────────
  // Gap reduced: with 2-line headline the sub sits tighter and higher.
  const SUB_FONT = Math.round(CW * 0.030);
  const SUB_W    = Math.round(CW * 0.78);
  const SUB_X    = Math.round((CW - SUB_W) / 2);
  const SUB_Y    = Math.min(
    Math.round(HEADLINE_Y + HEADLINE_H + CW * 0.018),
    Math.round(CH * 0.40),
  );
  const SUB_H = Math.ceil(SUB_FONT * 1.4 * 2) + 8;

  // ── Badge: small overline / tagline above the headline ───────────────────
  const BADGE_FONT = Math.round(CW * 0.016);
  const BADGE_W    = Math.round(CW * 0.50);
  const BADGE_X    = Math.round((CW - BADGE_W) / 2);
  const BADGE_Y    = Math.round(CH * 0.035);
  const BADGE_H    = Math.ceil(BADGE_FONT + 12) + 4;

  // ── CTA: pill button at the very bottom, overlaid on the person ──────────
  const CTA_FONT     = Math.round(CW * 0.022);
  const CTA_W        = Math.round(CW * 0.55);
  const CTA_X        = Math.round((CW - CTA_W) / 2);
  const CTA_Y        = Math.round(CH * 0.875);
  const CTA_H        = CTA_FONT + 40; // height includes pill padding
  const ctaContent   = (copy as Record<string, unknown>).cta as string | undefined;
  const ctaPillColor = (copy as Record<string, unknown>).primaryColor as string | undefined ?? "#1A1A1A";

  return {
    version: "1",
    canvas: { width: CW, height: CH },
    safeArea: { margin: Math.round(CW * 0.03) },

    // No product — scene generated by PRODUCT_IA (sceneMode with zoneHint="top")
    product: {
      anchor: "custom",
      x: 0,
      y: 0,
      width: 0,
      height: 0,
      scale: 1,
      rotation: 0,
    },

    overlays: [],

    textBlocks: [
      // ── BADGE: small overline at very top (centered) ──────────────────────
      ...(copy.badge
        ? [
            {
              id: "badge" as const,
              content: copy.badge,
              x: BADGE_X,
              y: BADGE_Y,
              w: BADGE_W,
              h: BADGE_H,
              align: "center" as const,
              fontFamily: "Montserrat",
              fontWeight: "400" as const,
              fontSize: BADGE_FONT,
              color: "#3C2415",
              lineHeight: 1,
              letterSpacing: 0.02,
              maxLines: 1,
              textTransform: "none" as const,
            },
          ]
        : []),

      // ── HEADLINE: huge, centered at top ──────────────────────────────────
      ...(copy.headline
        ? [
            {
              id: "headline" as const,
              content: balancedHeadline,
              x: HEADLINE_X,
              y: HEADLINE_Y,
              w: HEADLINE_W,
              h: HEADLINE_H,
              align: "center" as const,
              fontFamily: "Lora",
              fontWeight: "700" as const,
              boldWeight: "900",
              fontSize: HEADLINE_FONT,
              color: "#1A1A1A",
              lineHeight: 1.1,
              letterSpacing: -0.01,
              maxLines: 2,
              textTransform: "none" as const,
            },
          ]
        : []),

      // ── SUBHEADLINE: centered, below headline ─────────────────────────────
      ...(copy.subheadline
        ? [
            {
              id: "subheadline" as const,
              content: copy.subheadline,
              x: SUB_X,
              y: SUB_Y,
              w: SUB_W,
              h: SUB_H,
              align: "center" as const,
              fontFamily: "Montserrat",
              fontWeight: "500" as const,
              boldWeight: "700",
              fontSize: SUB_FONT,
              color: "#2A2A2A",
              lineHeight: 1.4,
              letterSpacing: 0,
              maxLines: 2,
              textTransform: "none" as const,
              textBalance: true,
            },
          ]
        : []),

      // ── CTA: pill button at the very bottom, overlaid on the person ───────
      ...(ctaContent
        ? [
            {
              id: "cta" as const,
              content: ctaContent,
              x: CTA_X,
              y: CTA_Y,
              w: CTA_W,
              h: CTA_H,
              align: "center" as const,
              fontFamily: "Montserrat",
              fontWeight: "700" as const,
              fontSize: CTA_FONT,
              color: "#FFFFFF",
              lineHeight: 1,
              letterSpacing: 0.02,
              maxLines: 1,
              textTransform: "none" as const,
              background: {
                type: "pill",
                color: ctaPillColor,
                radius: 32,
                padding: 16,
                opacity: 1,
              },
            },
          ]
        : []),
    ],

    confidence: 1,
    rationale:
      "editorial-center-top — Headline + subheadline centrados en la parte superior, persona lifestyle llena el ancho completo inferior. Sin producto.",
    warnings: [
      "No product — scene generated by PRODUCT_IA (sceneMode, zoneHint=top).",
      "Text zone: top 48%. Person zone: bottom 50%. Sharp bulletproof protection applied.",
    ],
  } as unknown as LayoutSpec;
}
