/**
 * Template: Editorial Lifestyle Left (con lado dinámico)
 *
 * Inspirado en "Every Skin Tells a Story" — close-up lifestyle editorial:
 *   TEXTO (0%–48% ó 52%–100%): Headline enorme (Lora italic bold) + subheadline
 *   ESCENA (el lado opuesto):   persona/escena generada por IA (PRODUCT_IA sceneMode)
 *   BADGE:                      URL / tagline (esquina inferior del lado del texto)
 *
 * Sin producto — puro editorial de marca. La escena es generada por Gemini.
 * El lado del texto lo decide la IA de copy mediante el campo `textSide`.
 *
 * TemplateCopy fields:
 *   headline     — claim principal enorme (ej: "Every Skin Tells a Story.")
 *   subheadline  — bajada complementaria (ej: "We Just Help It Glow.")
 *   badge        — URL o tagline (esquina inferior)
 *   sceneAction  — descripción de la persona/escena para Gemini
 *   textSide     — "left" | "right" — la IA elige el lado del texto (default "left")
 */

import type { LayoutSpec } from "../layoutSpec";
import type { TemplateCopy } from "./classic-editorial";

// ── Layout builder ────────────────────────────────────────────────────────────

export function buildEditorialLifestyleLeftLayout(
  copy: TemplateCopy,
  canvas = { width: 1080, height: 1080 },
): LayoutSpec {
  const { width: CW, height: CH } = canvas;

  // ── Side decision (AI-driven) ─────────────────────────────────────────────
  const textSide = ((copy as Record<string, unknown>).textSide as string) === "right"
    ? "right"
    : "left";
  const isRight = textSide === "right";

  // ── Headline: responsive font size based on word count ───────────────────
  // Short headlines (≤4 words) get the dramatic large size.
  // Longer headlines scale down so they don't overflow into the subheadline area.
  const headlineWords  = (copy.headline ?? "").trim().split(/\s+/).filter(Boolean).length;
  const HEADLINE_FONT  = Math.round(
    CW * (headlineWords <= 4 ? 0.090 : headlineWords <= 6 ? 0.076 : 0.065)
  );
  const HEADLINE_W    = Math.round(CW * 0.46);
  const HEADLINE_X    = isRight
    ? Math.round(CW - CW * 0.04 - HEADLINE_W)   // ~CW * 0.50
    : Math.round(CW * 0.04);
  const HEADLINE_Y    = Math.round(CH * 0.28);
  const HEADLINE_H    = Math.ceil(HEADLINE_FONT * 1.1 * 5) + 12;

  // ── Subheadline: smaller, below headline ──────────────────────────────────
  const SUB_FONT = Math.round(CW * 0.032);
  const SUB_W    = Math.round(CW * 0.40); // safety margin: keeps ~6% gap from scene boundary
  const SUB_X    = isRight
    ? Math.round(CW - CW * 0.04 - SUB_W)        // ~CW * 0.52
    : Math.round(CW * 0.04);
  const SUB_Y    = Math.round(CH * 0.78);
  const SUB_H    = Math.ceil(SUB_FONT * 1.4 * 2) + 8;

  // ── Badge: bottom corner (same side as text) ──────────────────────────────
  const BADGE_FONT = Math.round(CW * 0.017);
  const BADGE_W    = Math.round(CW * 0.40);
  const BADGE_X    = isRight
    ? Math.round(CW - CW * 0.04 - BADGE_W)      // ~CW * 0.56
    : Math.round(CW * 0.04);
  const BADGE_Y    = Math.round(CH * 0.93);
  const BADGE_H    = Math.ceil(BADGE_FONT + 12) + 4;

  return {
    version: "1",
    canvas: { width: CW, height: CH },
    safeArea: { margin: Math.round(CW * 0.03) },

    // No product — scene generated by PRODUCT_IA
    product: {
      anchor: "custom",
      x: 0,
      y: 0,
      width: 0,
      height: 0,
      scale: 1,
      rotation: 0,
    },

    overlays: [],

    textBlocks: [
      // ── HEADLINE: huge, left ──────────────────────────────────────────────
      ...(copy.headline
        ? [
            {
              id: "headline" as const,
              content: copy.headline,
              x: HEADLINE_X,
              y: HEADLINE_Y,
              w: HEADLINE_W,
              h: HEADLINE_H,
              align: "left" as const,
              fontFamily: "Lora",
              fontWeight: "700" as const,
              boldWeight: "900",
              fontSize: HEADLINE_FONT,
              color: "#1A1A1A",
              lineHeight: 1.1,
              letterSpacing: -0.01,
              maxLines: 5,
              textTransform: "none" as const,
            },
          ]
        : []),

      // ── SUBHEADLINE: lighter, below ──────────────────────────────────────
      ...(copy.subheadline
        ? [
            {
              id: "subheadline" as const,
              content: copy.subheadline,
              x: SUB_X,
              y: SUB_Y,
              w: SUB_W,
              h: SUB_H,
              align: "left" as const,
              fontFamily: "Montserrat",
              fontWeight: "500" as const,
              boldWeight: "700",
              fontSize: SUB_FONT,
              color: "#2A2A2A",
              lineHeight: 1.4,
              letterSpacing: 0,
              maxLines: 2,
              textTransform: "none" as const,
            },
          ]
        : []),

      // ── BADGE: bottom-left ────────────────────────────────────────────────
      ...(copy.badge
        ? [
            {
              id: "badge" as const,
              content: copy.badge,
              x: BADGE_X,
              y: BADGE_Y,
              w: BADGE_W,
              h: BADGE_H,
              align: "left" as const,
              fontFamily: "Montserrat",
              fontWeight: "400" as const,
              fontSize: BADGE_FONT,
              color: "#3C2415",
              lineHeight: 1,
              letterSpacing: 0.01,
              maxLines: 1,
              textTransform: "none" as const,
            },
          ]
        : []),
    ],

    confidence: 1,
    rationale:
      "editorial-lifestyle-left — Huge headline LEFT, lifestyle scene RIGHT via PRODUCT_IA. Editorial beauty ad style. No product.",
    warnings: [
      "No product — scene generated by PRODUCT_IA (sceneMode).",
      "Headline on left column, scene fills right side.",
    ],
  } as unknown as LayoutSpec;
}
