/**
 * Template: Editorial Lifestyle Right
 *
 * Variación espejada de editorial-lifestyle-left:
 *   IZQUIERDA (0%–52%):  persona/escena generada por IA (PRODUCT_IA sceneMode)
 *   DERECHA (52%–100%):  Headline enorme + subheadline
 *   BOTTOM-RIGHT:        badge / URL pequeño
 *
 * Sin producto — puro editorial de marca.
 * copyZone = "right" → PRODUCT_IA genera la persona en el lado izquierdo.
 *
 * TemplateCopy fields:
 *   headline     — claim principal enorme
 *   subheadline  — bajada complementaria
 *   badge        — URL o tagline (bottom-right)
 *   sceneAction  — descripción de la persona/escena para Gemini
 */

import type { LayoutSpec } from "../layoutSpec";
import type { TemplateCopy } from "./classic-editorial";

// ── Layout builder ────────────────────────────────────────────────────────────

export function buildEditorialLifestyleRightLayout(
  copy: TemplateCopy,
  canvas = { width: 1080, height: 1080 },
): LayoutSpec {
  const { width: CW, height: CH } = canvas;

  // ── Headline: huge, right column, vertically centered ─────────────────────
  const HEADLINE_FONT = Math.round(CW * 0.09);
  const HEADLINE_W    = Math.round(CW * 0.46);
  const HEADLINE_X    = Math.round(CW * 0.52);
  const HEADLINE_Y    = Math.round(CH * 0.30);
  const HEADLINE_H    = Math.ceil(HEADLINE_FONT * 1.1 * 5) + 12;

  // ── Subheadline: smaller, below headline ──────────────────────────────────
  const SUB_FONT = Math.round(CW * 0.032);
  const SUB_W    = Math.round(CW * 0.44);
  const SUB_X    = Math.round(CW * 0.52);
  const SUB_Y    = Math.round(CH * 0.78);
  const SUB_H    = Math.ceil(SUB_FONT * 1.4 * 2) + 8;

  // ── Badge: bottom-right ───────────────────────────────────────────────────
  const BADGE_FONT = Math.round(CW * 0.017);
  const BADGE_W    = Math.round(CW * 0.40);
  const BADGE_X    = Math.round(CW * 0.56);
  const BADGE_Y    = Math.round(CH * 0.93);
  const BADGE_H    = Math.ceil(BADGE_FONT + 12) + 4;

  return {
    version: "1",
    canvas: { width: CW, height: CH },
    safeArea: { margin: Math.round(CW * 0.03) },

    // No product — scene generated by PRODUCT_IA
    product: {
      anchor: "custom",
      x: 0,
      y: 0,
      width: 0,
      height: 0,
      scale: 1,
      rotation: 0,
    },

    overlays: [],

    textBlocks: [
      // ── HEADLINE: huge, right ─────────────────────────────────────────────
      ...(copy.headline
        ? [
            {
              id: "headline" as const,
              content: copy.headline,
              x: HEADLINE_X,
              y: HEADLINE_Y,
              w: HEADLINE_W,
              h: HEADLINE_H,
              align: "left" as const,
              fontFamily: "Lora",
              fontWeight: "700" as const,
              fontSize: HEADLINE_FONT,
              color: "#1A1A1A",
              lineHeight: 1.1,
              letterSpacing: -0.01,
              maxLines: 5,
              textTransform: "none" as const,
            },
          ]
        : []),

      // ── SUBHEADLINE: lighter, below ──────────────────────────────────────
      ...(copy.subheadline
        ? [
            {
              id: "subheadline" as const,
              content: copy.subheadline,
              x: SUB_X,
              y: SUB_Y,
              w: SUB_W,
              h: SUB_H,
              align: "left" as const,
              fontFamily: "Montserrat",
              fontWeight: "500" as const,
              fontSize: SUB_FONT,
              color: "#2A2A2A",
              lineHeight: 1.4,
              letterSpacing: 0,
              maxLines: 2,
              textTransform: "none" as const,
            },
          ]
        : []),

      // ── BADGE: bottom-right ───────────────────────────────────────────────
      ...(copy.badge
        ? [
            {
              id: "badge" as const,
              content: copy.badge,
              x: BADGE_X,
              y: BADGE_Y,
              w: BADGE_W,
              h: BADGE_H,
              align: "right" as const,
              fontFamily: "Montserrat",
              fontWeight: "400" as const,
              fontSize: BADGE_FONT,
              color: "#3C2415",
              lineHeight: 1,
              letterSpacing: 0.01,
              maxLines: 1,
              textTransform: "none" as const,
            },
          ]
        : []),
    ],

    confidence: 1,
    rationale:
      "editorial-lifestyle-right — Huge headline RIGHT, lifestyle scene LEFT via PRODUCT_IA. Editorial beauty ad style. No product.",
    warnings: [
      "No product — scene generated by PRODUCT_IA (sceneMode).",
      "Headline on right column, scene fills left side.",
    ],
  } as unknown as LayoutSpec;
}
