/**
 * Template: Editorial Lifestyle Bottom
 *
 * Layout full-bleed con escena y texto grande abajo:
 *   ARRIBA (0%–65%):   persona/escena generada por IA (PRODUCT_IA sceneMode) full-bleed
 *   ABAJO (65%–100%):  Headline enorme centrado + subheadline debajo
 *   OVERLAY:           gradiente oscuro desde abajo para legibilidad de texto
 *
 * Sin producto — puro editorial de marca.
 * copyZone = "bottom" → PRODUCT_IA genera la persona ocupando la parte superior.
 *
 * TemplateCopy fields:
 *   headline     — claim principal enorme centrado
 *   subheadline  — bajada complementaria
 *   badge        — URL o tagline (bottom-center)
 *   sceneAction  — descripción de la persona/escena para Gemini
 */

import type { LayoutSpec } from "../layoutSpec";
import type { TemplateCopy } from "./classic-editorial";

// ── Layout builder ────────────────────────────────────────────────────────────

export function buildEditorialLifestyleBottomLayout(
  copy: TemplateCopy,
  canvas = { width: 1080, height: 1080 },
): LayoutSpec {
  const { width: CW, height: CH } = canvas;

  // ── Headline: huge, centered bottom area ──────────────────────────────────
  const HEADLINE_FONT = Math.round(CW * 0.075);
  const HEADLINE_W    = Math.round(CW * 0.88);
  const HEADLINE_X    = Math.round((CW - HEADLINE_W) / 2);
  const HEADLINE_Y    = Math.round(CH * 0.68);
  const HEADLINE_H    = Math.ceil(HEADLINE_FONT * 1.1 * 3) + 12;

  // ── Subheadline: smaller, below headline ──────────────────────────────────
  const SUB_FONT = Math.round(CW * 0.028);
  const SUB_W    = Math.round(CW * 0.70);
  const SUB_X    = Math.round((CW - SUB_W) / 2);
  const SUB_Y    = Math.round(CH * 0.88);
  const SUB_H    = Math.ceil(SUB_FONT * 1.4 * 2) + 8;

  // ── Badge: bottom-center ──────────────────────────────────────────────────
  const BADGE_FONT = Math.round(CW * 0.016);
  const BADGE_W    = Math.round(CW * 0.50);
  const BADGE_X    = Math.round((CW - BADGE_W) / 2);
  const BADGE_Y    = Math.round(CH * 0.95);
  const BADGE_H    = Math.ceil(BADGE_FONT + 12) + 4;

  return {
    version: "1",
    canvas: { width: CW, height: CH },
    safeArea: { margin: Math.round(CW * 0.03) },

    // No product — scene generated by PRODUCT_IA
    product: {
      anchor: "custom",
      x: 0,
      y: 0,
      width: 0,
      height: 0,
      scale: 1,
      rotation: 0,
    },

    // Dark gradient from bottom for text readability over the scene
    overlays: [
      {
        type: "linearGradient",
        x: 0,
        y: Math.round(CH * 0.50),
        w: CW,
        h: Math.round(CH * 0.50),
        direction: "bottom",
        color: "#000000",
        opacity: 0.55,
      },
    ],

    textBlocks: [
      // ── HEADLINE: huge, centered bottom ───────────────────────────────────
      ...(copy.headline
        ? [
            {
              id: "headline" as const,
              content: copy.headline,
              x: HEADLINE_X,
              y: HEADLINE_Y,
              w: HEADLINE_W,
              h: HEADLINE_H,
              align: "center" as const,
              fontFamily: "Lora",
              fontWeight: "700" as const,
              fontSize: HEADLINE_FONT,
              color: "#FFFFFF",
              lineHeight: 1.1,
              letterSpacing: -0.01,
              maxLines: 3,
              textTransform: "none" as const,
            },
          ]
        : []),

      // ── SUBHEADLINE: lighter, below ──────────────────────────────────────
      ...(copy.subheadline
        ? [
            {
              id: "subheadline" as const,
              content: copy.subheadline,
              x: SUB_X,
              y: SUB_Y,
              w: SUB_W,
              h: SUB_H,
              align: "center" as const,
              fontFamily: "Montserrat",
              fontWeight: "400" as const,
              fontSize: SUB_FONT,
              color: "#E8E8E8",
              lineHeight: 1.4,
              letterSpacing: 0.01,
              maxLines: 2,
              textTransform: "none" as const,
            },
          ]
        : []),

      // ── BADGE: bottom-center ──────────────────────────────────────────────
      ...(copy.badge
        ? [
            {
              id: "badge" as const,
              content: copy.badge,
              x: BADGE_X,
              y: BADGE_Y,
              w: BADGE_W,
              h: BADGE_H,
              align: "center" as const,
              fontFamily: "Montserrat",
              fontWeight: "400" as const,
              fontSize: BADGE_FONT,
              color: "#CCCCCC",
              lineHeight: 1,
              letterSpacing: 0.01,
              maxLines: 1,
              textTransform: "none" as const,
            },
          ]
        : []),
    ],

    confidence: 1,
    rationale:
      "editorial-lifestyle-bottom — Full-bleed lifestyle scene, huge headline at BOTTOM with dark gradient overlay. Editorial beauty ad style. No product.",
    warnings: [
      "No product — scene generated by PRODUCT_IA (sceneMode).",
      "Full-bleed scene with dark gradient at bottom for text readability.",
      "White text over dark gradient.",
    ],
  } as unknown as LayoutSpec;
}
