/**
 * Template: Persona Hero Bottom
 *
 * Inspirado en el estilo Huel — lifestyle ad con escena de personas en la parte inferior:
 *   PANEL SUPERIOR (~42%): fondo blanco sólido, todo centrado
 *     LOGO:        overlay centrado gestionado por composeWithTemplateBeta
 *     HEADLINE:    claim principal grande (Montserrat ExtraBold, centrado, oscuro, text-balance)
 *     SUBHEADLINE: bajada de beneficio (Montserrat Regular, centrado, gris, text-balance)
 *   ESCENA INFERIOR (~58%): foto lifestyle full-bleed con persona(s) + producto
 *     CTA:         botón pill centrado al pie de la escena
 *
 * TemplateCopy fields:
 *   headline    — claim principal (max 8 palabras, tipografía grande centrada)
 *   subheadline — línea de beneficio de apoyo (max 100 chars, 1-2 líneas)
 *   title       — texto del botón CTA (max 25 chars, ej: "Shop Now", "Quiero el mío")
 *   productPrompt — descripción de la escena con persona(s) sosteniendo el producto
 */

import type { LayoutSpec } from "../layoutSpec";
import type { TemplateCopy } from "./classic-editorial";

export function buildPersonaHeroBottomLayout(
  copy: TemplateCopy,
  canvas = { width: 1080, height: 1350 },
): LayoutSpec {
  const { width: CW, height: CH } = canvas;

  // ── White top panel height ────────────────────────────────────────────────
  const PANEL_H = Math.round(CH * 0.42);

  // ── HEADLINE: bold centered claim — max 2 lines, below logo area ─────────
  const headlineWords = (copy.headline ?? "").trim().split(/\s+/).filter(Boolean).length;
  const HL_FONT = Math.round(
    CW * (headlineWords <= 3 ? 0.068 : headlineWords <= 5 ? 0.057 : 0.047),
  );
  const HL_W = Math.round(CW * 0.88);
  const HL_X = Math.round((CW - HL_W) / 2);
  const HL_Y = Math.round(CH * 0.13); // ~176px — safely below logo at top
  const HL_H = Math.ceil(HL_FONT * 1.12 * 2) + 12; // max 2 lines

  // ── SUBHEADLINE: centered below headline ──────────────────────────────────
  const SUB_FONT = Math.round(CW * 0.030); // ~32px
  const SUB_W    = Math.round(CW * 0.78);
  const SUB_X    = Math.round((CW - SUB_W) / 2);
  const SUB_Y    = Math.round(CH * 0.295); // ~398px at 1350
  const SUB_H    = Math.ceil(SUB_FONT * 1.4 * 2) + 8;

  // ── CTA: pill button — centered at bottom of scene ───────────────────────
  const CTA_FONT    = Math.round(CW * 0.034); // ~37px (larger than before)
  const CTA_PADDING = 20;
  const CTA_W       = Math.round(CW * 0.44); // wider pill for bigger text
  const CTA_X       = Math.round((CW - CTA_W) / 2);
  const CTA_Y       = Math.round(CH * 0.875); // ~1181px at 1350
  const CTA_H       = Math.ceil(CTA_FONT * 1.2) + CTA_PADDING * 2;

  return {
    version: "1",
    canvas: { width: CW, height: CH },
    safeArea: { margin: Math.round(CW * 0.055) },

    // No independent product placement — scene generated by PRODUCT_IA
    product: {
      anchor: "custom",
      x: 0,
      y: 0,
      width: 0,
      height: 0,
      scale: 1,
      rotation: 0,
    },

    overlays: [
      {
        // White solid panel covering the top ~42%
        type: "solid",
        x: 0,
        y: 0,
        w: CW,
        h: PANEL_H,
        color: "#FFFFFF",
        opacity: 1,
      },
    ],

    textBlocks: [
      // ── HEADLINE: large bold centered ─────────────────────────────────────
      ...(copy.headline
        ? [
            {
              id: "headline" as const,
              content: copy.headline,
              x: HL_X,
              y: HL_Y,
              w: HL_W,
              h: HL_H,
              align: "center" as const,
              fontFamily: "Montserrat",
              fontWeight: "800" as const,
              fontSize: HL_FONT,
              color: "#111111",
              lineHeight: 1.1,
              letterSpacing: -0.02,
              maxLines: 2,
              textTransform: "none" as const,
              textBalance: true,
            },
          ]
        : []),

      // ── SUBHEADLINE: centered, below headline ────────────────────────────
      ...(copy.subheadline
        ? [
            {
              id: "subheadline" as const,
              content: copy.subheadline,
              x: SUB_X,
              y: SUB_Y,
              w: SUB_W,
              h: SUB_H,
              align: "center" as const,
              fontFamily: "Montserrat",
              fontWeight: "400" as const,
              fontSize: SUB_FONT,
              color: "#555555",
              lineHeight: 1.4,
              letterSpacing: 0,
              maxLines: 2,
              textTransform: "none" as const,
              textBalance: true,
            },
          ]
        : []),

      // ── CTA: pill button, centered at bottom of scene ────────────────────
      ...(copy.title
        ? [
            {
              id: "cta" as const,
              content: copy.title,
              x: CTA_X,
              y: CTA_Y,
              w: CTA_W,
              h: CTA_H,
              align: "center" as const,
              fontFamily: "Montserrat",
              fontWeight: "700" as const,
              fontSize: CTA_FONT,
              color: "#FFFFFF",
              lineHeight: 1,
              letterSpacing: 0.01,
              maxLines: 1,
              textTransform: "none" as const,
              background: {
                type: "pill" as const,
                color: "#1A2E1A",
                radius: 30,
                padding: CTA_PADDING,
                opacity: 1,
              },
            },
          ]
        : []),
    ],

    confidence: 1,
    rationale:
      "persona-hero-bottom — Huel-style lifestyle ad: white top panel centered (headline+subheadline), full-bleed lifestyle scene at bottom with person+product, CTA pill near bottom. Logo overlay handled separately.",
    warnings: [
      "White solid overlay covers TOP 42% — text renders in dark color on white.",
      "Person/group with product generated by PRODUCT_IA in the BOTTOM 60% of canvas.",
      "Use 'title' field for CTA button text.",
      "No badge text block — brand logo rendered via logo overlay system (centered at top).",
    ],
  } as unknown as LayoutSpec;
}
