/**
 * Template: Scene Placeholder Test
 *
 * Full-bleed scene with muted/opaque background (AI decides the mood),
 * oversized Bebas Neue headline at the top, and a CTA pill at the bottom:
 *   OVERLAY:   dark gradient top 40% → fades to transparent (ensures headline legibility on any bg)
 *   HEADLINE:  single powerful claim, Bebas Neue, uppercase, white, centered, top area
 *   CTA:       pill button, centered, bottom area, uses brand primaryColor
 *   LOGO:      top-left, auto-rendered by system
 *   SCENE:     full-bleed person scene generated by PRODUCT_IA
 *
 * No product layer. Background is muted/opaque (not forced dark cinematic).
 *
 * TemplateCopy fields:
 *   headline — single impactful claim, max 8 words
 *   cta      — CTA button text, max 20 chars
 */

import type { LayoutSpec } from "../layoutSpec";
import type { TemplateCopy } from "./classic-editorial";

// ── Text measurement (Bebas Neue condensed) ──────────────────────────────────

const CHAR_WIDTHS: Record<string, number> = {
  i: 0.25, l: 0.25, I: 0.28, "!": 0.28, ".": 0.28, ",": 0.28,
  "¿": 0.38, "?": 0.42, "@": 0.65,
  j: 0.28, f: 0.32, t: 0.35, r: 0.38,
  "1": 0.45, s: 0.48, c: 0.5, a: 0.52, e: 0.52, o: 0.55,
  n: 0.55, u: 0.55, z: 0.48, x: 0.5, v: 0.5, y: 0.5,
  k: 0.52, h: 0.55, b: 0.55, d: 0.55, p: 0.55, q: 0.55, g: 0.55,
  w: 0.72, m: 0.82,
  W: 0.95, M: 0.88, A: 0.65, B: 0.62, C: 0.65, D: 0.68,
  E: 0.55, F: 0.52, G: 0.7, H: 0.7, J: 0.45, K: 0.62, L: 0.52,
  N: 0.7, O: 0.72, P: 0.58, Q: 0.72, R: 0.62, S: 0.55,
  T: 0.58, U: 0.68, V: 0.62, X: 0.62, Y: 0.58, Z: 0.58,
  "0": 0.55, "2": 0.55, "3": 0.55, "4": 0.55, "5": 0.55,
  "6": 0.55, "7": 0.55, "8": 0.55, "9": 0.55,
  " ": 0.28, "-": 0.35, "%": 0.85, "&": 0.7,
  á: 0.52, é: 0.52, í: 0.25, ó: 0.55, ú: 0.55, ñ: 0.55,
  Á: 0.65, É: 0.55, Ó: 0.72, Ú: 0.68, Ñ: 0.7,
};

const DEFAULT_CW = 0.55;

// Must match textRenderer's FONT_FAMILY_FACTORS["bebas neue"] for consistent measurement
const BEBAS_FACTOR = 0.68;

function measureBebasWord(text: string, fontSize: number): number {
  let w = 0;
  for (const ch of text.toUpperCase())
    w += (CHAR_WIDTHS[ch] ?? DEFAULT_CW) * fontSize;
  return w * BEBAS_FACTOR;
}

function fitBebasToLines(
  text: string,
  maxWidth: number,
  maxLines: number,
  startSize: number,
  minSize: number,
): number {
  const words = text.toUpperCase().split(/\s+/).filter(Boolean);
  if (words.length === 0) return startSize;

  function countLines(size: number): number {
    const spaceW = measureBebasWord(" ", size);
    let lineWidth = 0;
    let lines = 1;
    for (const word of words) {
      const ww = measureBebasWord(word, size);
      if (lineWidth > 0 && lineWidth + spaceW + ww > maxWidth) {
        lines++;
        lineWidth = ww;
      } else {
        lineWidth = lineWidth === 0 ? ww : lineWidth + spaceW + ww;
      }
    }
    return lines;
  }

  let size = startSize;
  while (size > minSize && countLines(size) > maxLines) {
    size -= 2;
  }
  return size;
}

// ── Layout builder ────────────────────────────────────────────────────────────

export function buildScenePlaceholderTestLayout(
  copy: TemplateCopy,
  canvas = { width: 1080, height: 1080 },
): LayoutSpec {
  const { width: CW, height: CH } = canvas;
  const MARGIN = Math.round(CW * 0.01);

  // ── Headline sizing ──────────────────────────────────────────────────────
  const HL_W = CW;
  const HL_X = 0;
  const HL_MAX_FS = Math.round(CW * 0.085);
  const HL_MIN_FS = Math.round(CW * 0.04);
  const HL_LINE_H = 0.95;

  const MAX_HL_LINES = 2;
  const rawHeadline = copy.headline ?? "";
  const hlFontSize = fitBebasToLines(rawHeadline, HL_W, MAX_HL_LINES, HL_MAX_FS, HL_MIN_FS);

  const spaceW = measureBebasWord(" ", hlFontSize);
  const words = rawHeadline.toUpperCase().split(/\s+/).filter(Boolean);
  let lineWidth = 0;
  let lineCount = 1;
  for (const word of words) {
    const ww = measureBebasWord(word, hlFontSize);
    if (lineWidth > 0 && lineWidth + spaceW + ww > HL_W) {
      lineCount++;
      lineWidth = ww;
    } else {
      lineWidth = lineWidth === 0 ? ww : lineWidth + spaceW + ww;
    }
  }
  const hlLines = Math.min(lineCount, MAX_HL_LINES);
  const HL_H = Math.ceil(hlFontSize * HL_LINE_H * hlLines) + 20;
  const HL_Y = Math.round(CH * 0.10);

  // ── CTA pill ─────────────────────────────────────────────────────────────
  const CTA_FONT = Math.round(CW * 0.024);
  const CTA_W = Math.round(CW * 0.52);
  const CTA_X = Math.round((CW - CTA_W) / 2);
  const CTA_Y = Math.round(CH * 0.87);
  const CTA_H = CTA_FONT + 44;
  const ctaContent = (copy as Record<string, unknown>).cta as string | undefined;
  const ctaPillColor = (copy as Record<string, unknown>).primaryColor as string | undefined ?? "#1A1A1A";

  return {
    version: "1",
    canvas: { width: CW, height: CH },
    safeArea: { margin: MARGIN },

    product: {
      anchor: "custom",
      x: 0,
      y: 0,
      width: 0,
      height: 0,
      scale: 1,
      rotation: 0,
    },

    // Dark gradient at top ensures white headline is readable on any muted background
    overlays: [
      {
        type: "linearGradient",
        x: 0,
        y: 0,
        w: CW,
        h: Math.round(CH * 0.42),
        opacity: 0.72,
        color: "rgba(0,0,0,0.9)",
        direction: "bottom",
      },
    ],

    textBlocks: [
      // ── HEADLINE: Bebas Neue, centered, top area ─────────────────────────
      {
        id: "headline",
        content: rawHeadline,
        x: HL_X,
        y: HL_Y,
        w: HL_W,
        h: HL_H,
        align: "center",
        fontFamily: "Bebas Neue",
        fontWeight: "400",
        fontSize: hlFontSize,
        color: "#FFFFFF",
        lineHeight: HL_LINE_H,
        letterSpacing: 0.01,
        maxLines: MAX_HL_LINES,
        textTransform: "uppercase",
      },

      // ── CTA: pill button, centered, bottom area ───────────────────────────
      ...(ctaContent
        ? [
            {
              id: "cta" as const,
              content: ctaContent,
              x: CTA_X,
              y: CTA_Y,
              w: CTA_W,
              h: CTA_H,
              align: "center" as const,
              fontFamily: "Montserrat",
              fontWeight: "700" as const,
              fontSize: CTA_FONT,
              color: "#FFFFFF",
              lineHeight: 1,
              letterSpacing: 0.02,
              maxLines: 1,
              textTransform: "none" as const,
              background: {
                type: "pill",
                color: ctaPillColor,
                radius: 32,
                padding: 16,
                opacity: 1,
              },
            },
          ]
        : []),
    ],

    confidence: 1,
    rationale:
      "scene-placeholder-test — Copia de bebas-dynamicBg-cta para testear pipeline scene-with-placeholder.",
    warnings: [
      "Pipeline test: bg+escena+placeholder → copy → replace product con imagen real del usuario.",
    ],
  } as unknown as LayoutSpec;
}
