/**
 * Pipeline Schemas – Creative Mode System
 *
 * Zod schemas for all pipeline steps and outputs.
 * These schemas are used for:
 * - LLM output validation (generateSceneBrief, generateNarrativeAngle)
 * - Internal type safety
 * - API response typing
 */

import { z } from "zod";

/* ════════════════════════════════════════════════════════════════
   CREATIVE MODE
════════════════════════════════════════════════════════════════ */

/**
 * Creative mode determines the visual style and generation pipeline.
 * - clean: Minimalist editorial backgrounds (current default)
 * - lifestyle: Realistic contextual scenes with props
 * - narrative: Story-driven scenes with emotional triggers
 */
export const CreativeModeSchema = z.enum([
  "clean",
  "lifestyle",
  "narrative",
]);

export type CreativeMode = z.infer<typeof CreativeModeSchema>;

/**
 * Auto mode allows the system to decide based on strategic core.
 */
export const CreativeModeInputSchema = z.enum([
  "auto",
  "clean",
  "lifestyle",
  "narrative",
]);

export type CreativeModeInput = z.infer<typeof CreativeModeInputSchema>;

/* ════════════════════════════════════════════════════════════════
   SCENE BRIEF (LLM OUTPUT)
════════════════════════════════════════════════════════════════ */

/**
 * Scene brief generated by LLM for lifestyle/narrative modes.
 * Describes the environment, lighting, and composition.
 */
export const SceneBriefSchema = z.object({
  /** Environment type (e.g., "modern bathroom", "outdoor garden") */
  environment: z.string().min(3).max(100),
  
  /** Props in the scene (e.g., ["towel", "plant", "mirror"]) */
  props: z.array(z.string()).min(0).max(5).default([]),
  
  /** Lighting description (e.g., "soft morning light from window") */
  light: z.string().min(3).max(100),
  
  /** Mood/atmosphere (e.g., "calm", "energetic", "luxurious") */
  mood: z.string().min(3).max(50),
  
  /** Where text should be placed relative to scene */
  safe_text_area_preference: z.enum([
    "top",
    "bottom",
    "left",
    "right",
    "top_left",
    "top_right",
    "bottom_left",
    "bottom_right",
  ]).default("left"),
  
  /** Camera angle/perspective */
  camera: z.enum([
    "eye_level",
    "low_angle",
    "high_angle",
    "close_up",
    "medium_shot",
    "wide_shot",
  ]).default("eye_level"),
  
  /** Color palette hint (e.g., "warm neutrals", "cool blues") */
  color_palette: z.string().max(50).optional(),
  
  /** Depth of field preference */
  depth_of_field: z.enum([
    "shallow",    // Blurred background, focused product
    "medium",     // Some background detail
    "deep",       // Everything in focus
  ]).default("shallow"),
});

export type SceneBrief = z.infer<typeof SceneBriefSchema>;

/* ════════════════════════════════════════════════════════════════
   NARRATIVE ANGLE (LLM OUTPUT)
════════════════════════════════════════════════════════════════ */

/**
 * Narrative angle for story-driven creatives.
 * Only used for narrative mode.
 */
export const NarrativeAngleSchema = z.object({
  /** Type of angle/story being told */
  angle_type: z.enum([
    "routine",          // "Rutina AM", "Tu ritual nocturno"
    "transformation",   // "Antes / Después"
    "moment",           // "El momento perfecto"
    "lifestyle",        // "Tu mejor versión"
    "benefit_focus",    // "Hidratación profunda"
    "social_proof",     // "Lo que todos aman"
  ]),
  
  /** Emotional trigger for the creative */
  emotional_trigger: z.enum([
    "desire",       // Wanting something
    "fear_of_loss", // FOMO, scarcity
    "aspiration",   // Becoming better
    "comfort",      // Feeling good
    "urgency",      // Act now
    "curiosity",    // Want to know more
  ]),
  
  /** Time context for the narrative */
  time_of_day: z.enum([
    "morning",
    "afternoon",
    "evening",
    "night",
    "any",
  ]).default("any"),
  
  /** What the visual should focus on */
  visual_focus: z.enum([
    "product",      // Product is hero
    "result",       // The outcome/transformation
    "context",      // The usage context
    "emotion",      // The feeling
  ]).default("product"),
  
  /** Short tag/label for the creative (e.g., "Rutina AM") */
  tag_label: z.string().max(20).optional(),
});

export type NarrativeAngle = z.infer<typeof NarrativeAngleSchema>;

/* ════════════════════════════════════════════════════════════════
   LIGHT ZONES (CANVAS ANALYSIS)
════════════════════════════════════════════════════════════════ */

/**
 * A single zone in the light analysis grid.
 */
export const LightZoneSchema = z.object({
  /** Zone position */
  position: z.enum([
    "top_left",
    "top_center",
    "top_right",
    "middle_left",
    "middle_center",
    "middle_right",
    "bottom_left",
    "bottom_center",
    "bottom_right",
  ]),
  
  /** Zone rectangle */
  rect: z.object({
    x: z.number(),
    y: z.number(),
    w: z.number(),
    h: z.number(),
  }),
  
  /** Mean luminance (0-1) */
  luminance: z.number().min(0).max(1),
  
  /** Luminance variance (higher = more noisy) */
  variance: z.number().min(0),
  
  /** Score for text placement (0-1, higher = better) */
  textSafeScore: z.number().min(0).max(1),
  
  /** Recommended text color for this zone */
  recommendedTextColor: z.enum(["dark", "light"]),
  
  /** Whether backplate is recommended */
  needsBackplate: z.boolean(),
});

export type LightZone = z.infer<typeof LightZoneSchema>;

/**
 * Full light zone analysis result.
 */
export const LightZoneAnalysisSchema = z.object({
  /** All analyzed zones */
  zones: z.array(LightZoneSchema),
  
  /** Best zone for text placement */
  bestZone: LightZoneSchema.nullable(),
  
  /** Overall image characteristics */
  imageStats: z.object({
    meanLuminance: z.number(),
    variance: z.number(),
    dominantRegion: z.enum(["dark", "light", "mixed"]),
  }),
  
  /** Analysis time in ms */
  analysisTimeMs: z.number(),
});

export type LightZoneAnalysis = z.infer<typeof LightZoneAnalysisSchema>;

/* ════════════════════════════════════════════════════════════════
   TYPOGRAPHY PLAN (ALGORITHMIC)
════════════════════════════════════════════════════════════════ */

/**
 * Typography plan determined algorithmically from light zones.
 */
export const TypographyPlanSchema = z.object({
  /** Primary text color */
  textColor: z.enum(["dark", "light"]),
  
  /** Hex color for primary text */
  primaryHex: z.string(),
  
  /** Hex color for secondary text */
  secondaryHex: z.string(),
  
  /** Shadow configuration */
  shadow: z.object({
    enabled: z.boolean(),
    color: z.string().optional(),
    blur: z.number().optional(),
    offsetX: z.number().optional(),
    offsetY: z.number().optional(),
  }),
  
  /** Overlay gradient for text legibility */
  overlayGradient: z.object({
    enabled: z.boolean(),
    direction: z.enum(["top", "bottom", "left", "right"]).optional(),
    opacity: z.number().min(0).max(1).optional(),
    color: z.string().optional(),
  }),
  
  /** Recommended text alignment */
  alignment: z.enum(["left", "center", "right"]),
  
  /** Recommended position */
  position: z.enum([
    "top_left",
    "top_center",
    "top_right",
    "bottom_left",
    "bottom_center",
    "bottom_right",
    "middle_left",
    "middle_right",
  ]),
  
  /** Whether backplate is recommended */
  useBackplate: z.boolean(),
});

export type TypographyPlan = z.infer<typeof TypographyPlanSchema>;

/* ════════════════════════════════════════════════════════════════
   PIPELINE CONTEXT
════════════════════════════════════════════════════════════════ */

/**
 * Full pipeline context passed between steps.
 */
export const PipelineContextSchema = z.object({
  /** Resolved creative mode */
  mode: CreativeModeSchema,
  
  /** Scene brief (lifestyle/narrative only) */
  sceneBrief: SceneBriefSchema.nullable(),
  
  /** Narrative angle (narrative only) */
  narrativeAngle: NarrativeAngleSchema.nullable(),
  
  /** Light zone analysis */
  lightZones: LightZoneAnalysisSchema.nullable(),
  
  /** Typography plan */
  typographyPlan: TypographyPlanSchema.nullable(),
  
  /** Background image data URL */
  backgroundDataUrl: z.string().nullable(),
  
  /** Foreground blur data URL (optional) */
  foregroundDataUrl: z.string().nullable().optional(),
});

export type PipelineContext = z.infer<typeof PipelineContextSchema>;

/* ════════════════════════════════════════════════════════════════
   TEMPLATE IDS (EXTENDED)
════════════════════════════════════════════════════════════════ */

/**
 * Extended template IDs including new lifestyle/narrative templates.
 */
export const ExtendedTemplateIdSchema = z.enum([
  // Existing templates
  "T_SPLIT_EDITORIAL_V1",
  "T_BADGE_OFFER_V1",
  "T_BEFORE_AFTER_V1",
  "T_QUOTE_TESTIMONIAL_V1",
  // New templates
  "T_LIFESTYLE_HERO_V1",
  "T_NARRATIVE_HERO_V1",
]);

export type ExtendedTemplateId = z.infer<typeof ExtendedTemplateIdSchema>;

/* ════════════════════════════════════════════════════════════════
   RESPONSE METADATA
════════════════════════════════════════════════════════════════ */

/**
 * Extended metadata for API response.
 */
export const CreativeMetadataSchema = z.object({
  /** Creative mode used */
  mode: CreativeModeSchema,
  
  /** Scene brief (if generated) */
  scene: SceneBriefSchema.nullable().optional(),
  
  /** Narrative angle (if generated) */
  narrative: NarrativeAngleSchema.nullable().optional(),
  
  /** Typography plan used */
  typography: TypographyPlanSchema.nullable().optional(),
  
  /** Template ID used */
  templateId: ExtendedTemplateIdSchema,
});

export type CreativeMetadata = z.infer<typeof CreativeMetadataSchema>;
